/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerId = IDL.Nat;
export const Time = IDL.Int;
export const AppointmentId = IDL.Nat;
export const JobId = IDL.Nat;
export const EstimateId = IDL.Nat;
export const Appointment = IDL.Record({
  'scheduledDate' : Time,
  'jobType' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'customerId' : CustomerId,
  'appointmentId' : AppointmentId,
});
export const Customer = IDL.Record({
  'jobHistory' : IDL.Vec(JobId),
  'name' : IDL.Text,
  'physicalAddress' : IDL.Text,
  'customerId' : CustomerId,
  'emailAddress' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const Material = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitCost' : IDL.Nat,
});
export const Estimate = IDL.Record({
  'totalMaterialCost' : IDL.Nat,
  'laborHours' : IDL.Nat,
  'estimateId' : EstimateId,
  'creationDate' : Time,
  'laborHourlyRate' : IDL.Nat,
  'totalEstimate' : IDL.Nat,
  'squareFootage' : IDL.Nat,
  'totalLaborCost' : IDL.Nat,
  'materials' : IDL.Vec(Material),
  'pricePerSquareFoot' : IDL.Nat,
});
export const JobStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Job = IDL.Record({
  'status' : JobStatus,
  'serviceDate' : Time,
  'serviceType' : IDL.Text,
  'issuesFound' : IDL.Text,
  'jobId' : JobId,
  'customerId' : CustomerId,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppointment' : IDL.Func(
      [CustomerId, Time, IDL.Text, IDL.Nat],
      [AppointmentId],
      [],
    ),
  'createCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CustomerId],
      [],
    ),
  'createJob' : IDL.Func([CustomerId, Time, IDL.Text, IDL.Text], [JobId], []),
  'deleteEstimate' : IDL.Func([EstimateId], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllEstimates' : IDL.Func([], [IDL.Vec(Estimate)], ['query']),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getAppointment' : IDL.Func([AppointmentId], [Appointment], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [Customer], ['query']),
  'getEstimate' : IDL.Func([EstimateId], [Estimate], ['query']),
  'getJob' : IDL.Func([JobId], [Job], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveEstimate' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(Material), IDL.Nat, IDL.Nat],
      [EstimateId],
      [],
    ),
  'updateEstimate' : IDL.Func(
      [EstimateId, IDL.Nat, IDL.Nat, IDL.Vec(Material), IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateJobStatus' : IDL.Func([JobId, JobStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerId = IDL.Nat;
  const Time = IDL.Int;
  const AppointmentId = IDL.Nat;
  const JobId = IDL.Nat;
  const EstimateId = IDL.Nat;
  const Appointment = IDL.Record({
    'scheduledDate' : Time,
    'jobType' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'customerId' : CustomerId,
    'appointmentId' : AppointmentId,
  });
  const Customer = IDL.Record({
    'jobHistory' : IDL.Vec(JobId),
    'name' : IDL.Text,
    'physicalAddress' : IDL.Text,
    'customerId' : CustomerId,
    'emailAddress' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const Material = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitCost' : IDL.Nat,
  });
  const Estimate = IDL.Record({
    'totalMaterialCost' : IDL.Nat,
    'laborHours' : IDL.Nat,
    'estimateId' : EstimateId,
    'creationDate' : Time,
    'laborHourlyRate' : IDL.Nat,
    'totalEstimate' : IDL.Nat,
    'squareFootage' : IDL.Nat,
    'totalLaborCost' : IDL.Nat,
    'materials' : IDL.Vec(Material),
    'pricePerSquareFoot' : IDL.Nat,
  });
  const JobStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Job = IDL.Record({
    'status' : JobStatus,
    'serviceDate' : Time,
    'serviceType' : IDL.Text,
    'issuesFound' : IDL.Text,
    'jobId' : JobId,
    'customerId' : CustomerId,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppointment' : IDL.Func(
        [CustomerId, Time, IDL.Text, IDL.Nat],
        [AppointmentId],
        [],
      ),
    'createCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CustomerId],
        [],
      ),
    'createJob' : IDL.Func([CustomerId, Time, IDL.Text, IDL.Text], [JobId], []),
    'deleteEstimate' : IDL.Func([EstimateId], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllEstimates' : IDL.Func([], [IDL.Vec(Estimate)], ['query']),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getAppointment' : IDL.Func([AppointmentId], [Appointment], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [Customer], ['query']),
    'getEstimate' : IDL.Func([EstimateId], [Estimate], ['query']),
    'getJob' : IDL.Func([JobId], [Job], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveEstimate' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(Material), IDL.Nat, IDL.Nat],
        [EstimateId],
        [],
      ),
    'updateEstimate' : IDL.Func(
        [EstimateId, IDL.Nat, IDL.Nat, IDL.Vec(Material), IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateJobStatus' : IDL.Func([JobId, JobStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };