/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'scheduledDate' : Time,
  'jobType' : string,
  'durationMinutes' : bigint,
  'customerId' : CustomerId,
  'appointmentId' : AppointmentId,
}
export type AppointmentId = bigint;
export interface Customer {
  'jobHistory' : Array<JobId>,
  'name' : string,
  'physicalAddress' : string,
  'customerId' : CustomerId,
  'emailAddress' : string,
  'phoneNumber' : string,
}
export type CustomerId = bigint;
export interface Estimate {
  'totalMaterialCost' : bigint,
  'laborHours' : bigint,
  'estimateId' : EstimateId,
  'creationDate' : Time,
  'laborHourlyRate' : bigint,
  'totalEstimate' : bigint,
  'squareFootage' : bigint,
  'totalLaborCost' : bigint,
  'materials' : Array<Material>,
  'pricePerSquareFoot' : bigint,
}
export type EstimateId = bigint;
export interface Job {
  'status' : JobStatus,
  'serviceDate' : Time,
  'serviceType' : string,
  'issuesFound' : string,
  'jobId' : JobId,
  'customerId' : CustomerId,
}
export type JobId = bigint;
export type JobStatus = { 'scheduled' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Material {
  'name' : string,
  'quantity' : bigint,
  'unitCost' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppointment' : ActorMethod<
    [CustomerId, Time, string, bigint],
    AppointmentId
  >,
  'createCustomer' : ActorMethod<[string, string, string, string], CustomerId>,
  'createJob' : ActorMethod<[CustomerId, Time, string, string], JobId>,
  'deleteEstimate' : ActorMethod<[EstimateId], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllEstimates' : ActorMethod<[], Array<Estimate>>,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getAppointment' : ActorMethod<[AppointmentId], Appointment>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[CustomerId], Customer>,
  'getEstimate' : ActorMethod<[EstimateId], Estimate>,
  'getJob' : ActorMethod<[JobId], Job>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveEstimate' : ActorMethod<
    [bigint, bigint, Array<Material>, bigint, bigint],
    EstimateId
  >,
  'updateEstimate' : ActorMethod<
    [EstimateId, bigint, bigint, Array<Material>, bigint, bigint],
    undefined
  >,
  'updateJobStatus' : ActorMethod<[JobId, JobStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];